import importlib.util
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "check_figure_provenance.py"


def load_checker():
    spec = importlib.util.spec_from_file_location("check_figure_provenance", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules["check_figure_provenance"] = module
    spec.loader.exec_module(module)
    return module


def test_empty_directory_passes(tmp_path):
    checker = load_checker()
    assert checker.check(tmp_path) == []


def test_figure_without_provenance_fails(tmp_path):
    checker = load_checker()
    (tmp_path / "plot.png").write_bytes(b"x")
    missing = checker.check(tmp_path)
    assert len(missing) == 1
    assert "plot.png" in missing[0]


def test_sibling_provenance_passes(tmp_path):
    checker = load_checker()
    (tmp_path / "plot.png").write_bytes(b"x")
    (tmp_path / "plot.provenance.md").write_text("source: foo.py\n", encoding="utf-8")
    assert checker.check(tmp_path) == []


def test_index_in_same_directory_passes(tmp_path):
    checker = load_checker()
    (tmp_path / "plot.png").write_bytes(b"x")
    (tmp_path / "figure_provenance.md").write_text(
        "- plot.png: generated by foo.py\n", encoding="utf-8"
    )
    assert checker.check(tmp_path) == []


def test_index_in_ancestor_directory_passes(tmp_path):
    checker = load_checker()
    figures = tmp_path / "outputs" / "figures"
    figures.mkdir(parents=True)
    (figures / "plot.png").write_bytes(b"x")
    (tmp_path / "figure_provenance.md").write_text(
        "- plot.png: generated by foo.py\n", encoding="utf-8"
    )
    assert checker.check(tmp_path) == []


def test_index_must_mention_figure_filename(tmp_path):
    checker = load_checker()
    (tmp_path / "plot.png").write_bytes(b"x")
    (tmp_path / "figure_provenance.md").write_text(
        "- other.png: generated by bar.py\n", encoding="utf-8"
    )
    missing = checker.check(tmp_path)
    assert len(missing) == 1


def test_multiple_extensions_detected(tmp_path):
    checker = load_checker()
    for name in ("a.png", "b.pdf", "c.svg", "d.jpg", "e.jpeg"):
        (tmp_path / name).write_bytes(b"x")
    missing = checker.check(tmp_path)
    assert len(missing) == 5


def test_main_returns_zero_when_clean(tmp_path):
    checker = load_checker()
    assert checker.main(["--root", str(tmp_path)]) == 0


def test_main_returns_one_when_missing(tmp_path):
    checker = load_checker()
    (tmp_path / "plot.png").write_bytes(b"x")
    assert checker.main(["--root", str(tmp_path)]) == 1
