#!/usr/bin/env python3
"""Roll up Context Summary blocks from all paper reviews into one summary file.

For long literature passes the Lead Agent only needs the compact
Context Summary block from each review note for most replanning decisions.
Loading 17 full reviews (200-400 lines each) into context is wasteful when
the summary alone (10-15 lines each) is enough until a specific paper needs a
deep dive.

This script scans `<run-dir>/literature/reviews/*.md`, extracts the block
between `<!-- context-summary:start -->` and `<!-- context-summary:end -->`,
and writes the rolled-up output to `<run-dir>/literature/summary.md`.

Usage:
    python scripts/compile_literature_summary.py --project <project-dir>
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _project_root as project_root_mod  # noqa: E402


START_MARKER = "<!-- context-summary:start -->"
END_MARKER = "<!-- context-summary:end -->"
BLOCK_RE = re.compile(
    r"<!--\s*context-summary:start\s*-->\s*\n(.*?)\n\s*<!--\s*context-summary:end\s*-->",
    re.DOTALL,
)


@dataclass(frozen=True)
class ReviewSummary:
    path: Path
    block: str | None
    missing_reason: str | None


def extract_block(text: str) -> str | None:
    match = BLOCK_RE.search(text)
    if not match:
        return None
    return match.group(1).strip()


def scan_reviews(reviews_dir: Path) -> list[ReviewSummary]:
    results: list[ReviewSummary] = []
    for path in sorted(reviews_dir.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        block = extract_block(text)
        if block is None:
            results.append(
                ReviewSummary(
                    path=path,
                    block=None,
                    missing_reason=f"missing markers ({START_MARKER} / {END_MARKER})",
                )
            )
        else:
            results.append(ReviewSummary(path=path, block=block, missing_reason=None))
    return results


def build_summary_document(run_dir: Path, summaries: list[ReviewSummary]) -> str:
    header = [
        "# Literature Context Summary",
        "",
        "Auto-generated by `scripts/compile_literature_summary.py`. Each section is the",
        "`Context Summary` block from a paper review note. To update, regenerate this file",
        "rather than editing it by hand — edits will be overwritten.",
        "",
        f"- Run directory: `{run_dir.as_posix()}`",
        f"- Reviews scanned: {len(summaries)}",
        f"- Missing summary blocks: {sum(1 for s in summaries if s.block is None)}",
        "",
        "---",
        "",
    ]
    body: list[str] = []
    for entry in summaries:
        try:
            run_rel = entry.path.relative_to(run_dir).as_posix()
        except ValueError:
            run_rel = entry.path.as_posix()
        # Summary lives at <run>/literature/summary.md; reviews at <run>/literature/reviews/<name>.md
        link_target = f"reviews/{entry.path.name}"
        body.append(f"## [{entry.path.stem}]({link_target})")
        body.append("")
        body.append(f"- Review note: `{run_rel}`")
        body.append("")
        if entry.block:
            body.append(entry.block)
        else:
            body.append(f"> ⚠ {entry.missing_reason}")
        body.append("")
    return "\n".join(header + body).rstrip() + "\n"


def compile_summary(run_dir: Path) -> tuple[Path, int]:
    reviews_dir = run_dir / "literature" / "reviews"
    if not reviews_dir.is_dir():
        raise FileNotFoundError(f"No reviews directory found at {reviews_dir}")
    summaries = scan_reviews(reviews_dir)
    output = run_dir / "literature" / "summary.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_summary_document(run_dir, summaries), encoding="utf-8")
    missing = sum(1 for s in summaries if s.block is None)
    return output, missing


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--project", "--run",
        dest="project",
        type=Path,
        default=None,
        help="Project root directory. Default: walk up from cwd looking for "
             "the `.research-harness` marker. `--run` kept as alias for one release.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        project = project_root_mod.resolve_project(args.project, require=True)
    except project_root_mod.ProjectRootNotFoundError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    try:
        output, missing = compile_summary(project)
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    print(f"wrote {output}")
    if missing:
        print(f"warning: {missing} review(s) missing Context Summary markers")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
