#!/usr/bin/env python3
"""Scaffold a Physics Research Harness project in the current directory.

After v3 the project root IS the research root — there is no
`ResearchPartner-runs/<date>-<slug>/` wrapping directory anymore. This
script creates the harness directory tree directly inside the project
and writes a `.research-harness` marker file at the root so every gate
script can locate the project from any subdirectory.

For a single-thread project (most common) you run this once from the
project root and never again::

    cd MyPhysicsProject
    python <path-to-harness>/scripts/init_research_project.py

For a multi-thread project where you want two parallel research threads
under sibling subdirectories::

    python <path-to-harness>/scripts/init_research_project.py --project ./hvg-baseline
    python <path-to-harness>/scripts/init_research_project.py --project ./dhvg-extension

Each thread gets its own `.research-harness` marker, its own docs/,
literature/, src/, outputs/, etc. — the harness scripts treat them as
independent projects.

Layout version: 3
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(_SCRIPTS_DIR))
import _layout as layout  # noqa: E402
import _project_root as project_root_mod  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]

# ── Template sources (harness-relative) ──────────────────────────────────────
LIVE_TEMPLATE = ROOT / "docs" / "run_templates" / "live_workflow_diagram_template.md"
PACKET_TEMPLATE = ROOT / "docs" / "run_templates" / "research_run_packet_template.md"
CARTOGRAPHER_UPDATE_TEMPLATE = (
    ROOT / "docs" / "run_templates" / "cartographer_update_template.md"
)
ORIENT_NOTE_TEMPLATE = ROOT / "docs" / "run_templates" / "orient_note_template.md"
INTERVIEW_NOTES_TEMPLATE = ROOT / "docs" / "run_templates" / "interview_notes_template.md"
MODEL_SPEC_TEMPLATE = ROOT / "docs" / "run_templates" / "model_spec_template.md"
BASELINE_STRATEGY_TEMPLATE = (
    ROOT / "docs" / "run_templates" / "baseline_strategy_template.md"
)
PROJECT_README_TEMPLATE = ROOT / "docs" / "run_templates" / "run_readme_template.md"
LITERATURE_REVIEW_TEMPLATE = ROOT / "docs" / "literature" / "literature_review_template.md"
PAPER_REQUEST_TEMPLATE = ROOT / "docs" / "literature" / "paper_request_queue.md"
REPLANNING_MEMO_TEMPLATE = ROOT / "docs" / "literature" / "replanning_memo_template.md"
PAPER_REVIEW_INDEX_TEMPLATE = (
    ROOT / "docs" / "literature" / "paper_review_index_template.md"
)

# ── Files created from inline content ────────────────────────────────────────
INITIAL_GATES = {
    "baseline_registry.md": "# Baseline Registry\n\n- Project baseline target:\n",
    "validation_log.md": (
        "# Validation Log\n\n"
        "| Date | Command | Result | Evidence |\n"
        "|---|---|---|---|\n"
    ),
}

INITIAL_PLAN = {
    "research_plan.md": "# Research Plan\n\n- Initial plan seed:\n",
    "research_question.md": (
        "# Research Question\n\n"
        "<!-- One line: what is this project about? -->\n"
    ),
}

INITIAL_PROCESS = {
    "researcher_review_log.md": (
        "# Researcher Review Log\n\n"
        "| Date | Evidence Shown | Decision | Follow-up |\n"
        "|---|---|---|---|\n"
    ),
    "research_retrospective.md": (
        "# Research Retrospective\n\n"
        "- Reusable artifact:\n"
        "- Next smallest useful iteration:\n"
    ),
}

_GITIGNORE_CONTENT = """\
# Research project .gitignore — auto-generated by init_research_project.py.
# Excludes recomputable / session-local data; everything else IS committed.

cache/
logs/
errors/
literature/pdfs/
# Generated outputs — live at project root, not in docs/
workflow_map.live.json
workflow_map.html
# Legacy docs-level artifacts from older harness versions
docs/workflow_map.html
docs/workflow_map.json
docs/workflow_map.live.json
"""

# Claude Code hook registration.  Written to .claude/settings.local.json so
# that Write/Edit/Agent tool calls automatically trigger workflow_hooks.py and
# keep live_workflow_diagram.md / workflow_map.live.json in sync without
# requiring the AI to call update scripts manually.
_CLAUDE_SETTINGS_CONTENT = """\
{
  "permissions": {
    "allow": []
  },
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Agent",
        "hooks": [
          {"type": "command", "command": "python scripts/enforce_gate_sequence.py"},
          {"type": "command", "command": "python scripts/workflow_hooks.py pre"},
          {"type": "command", "command": "python scripts/check_peer_review_invocation.py"}
        ]
      },
      {
        "matcher": "Write|Edit",
        "hooks": [
          {"type": "command", "command": "python scripts/check_src_write_authorization.py"},
          {"type": "command", "command": "python scripts/workflow_hooks.py pre"}
        ]
      },
      {
        "matcher": "Bash|PowerShell",
        "hooks": [
          {"type": "command", "command": "python scripts/check_bash_code_write.py"}
        ]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "Agent",
        "hooks": [
          {"type": "command", "command": "python scripts/workflow_hooks.py post"}
        ]
      },
      {
        "matcher": "Write|Edit",
        "hooks": [
          {"type": "command", "command": "python scripts/workflow_hooks.py post"}
        ]
      },
      {
        "matcher": "Bash|PowerShell",
        "hooks": [
          {"type": "command", "command": "python scripts/workflow_hooks.py post"}
        ]
      }
    ]
  }
}
"""


def scaffold_project(project: Path | str = ".") -> Path:
    """Create the harness directory tree at the given project root.

    Idempotent: re-running on an existing project tops up missing files
    and refreshes the `.research-harness` marker but leaves user-edited
    artefacts untouched.
    """
    project = Path(project).resolve()
    project.mkdir(parents=True, exist_ok=True)

    # ── Create directory tree ─────────────────────────────────────────────────
    for d in [
        layout.gates_dir(project),
        layout.plan_dir(project),
        layout.process_dir(project),
        layout.literature_dir(project),
        layout.meetings_dir(project),
        layout.checkpoints_dir(project),
        layout.claims_dir(project),
        layout.model_versions_dir(project),
        layout.literature_pdf_dir(project),
        layout.literature_reviews_dir(project),
        layout.literature_extracted_dir(project),
        layout.src_dir(project),
        layout.outputs_dir(project) / "figures",
        layout.outputs_dir(project) / "data",
        layout.outputs_dir(project) / "tables",
        layout.cache_dir(project),
        layout.logs_dir(project),
        layout.errors_dir(project),
    ]:
        d.mkdir(parents=True, exist_ok=True)

    # ── Copy template files → docs/gates/ ────────────────────────────────────
    gates = layout.gates_dir(project)
    _copy_if_absent(ORIENT_NOTE_TEMPLATE, gates / "orient_note.md")
    _copy_if_absent(INTERVIEW_NOTES_TEMPLATE, gates / "interview_notes.md")

    # ── Copy template files → docs/plan/ ─────────────────────────────────────
    plan = layout.plan_dir(project)
    _copy_if_absent(MODEL_SPEC_TEMPLATE, plan / "model_spec.md")
    _copy_if_absent(BASELINE_STRATEGY_TEMPLATE, plan / "baseline_strategy.md")

    # ── Copy template files → docs/process/ ──────────────────────────────────
    process = layout.process_dir(project)
    _copy_if_absent(LIVE_TEMPLATE, process / "live_workflow_diagram.md")
    _copy_if_absent(CARTOGRAPHER_UPDATE_TEMPLATE, process / "cartographer_update_template.md")

    # ── Copy template files → docs/literature/ ───────────────────────────────
    lit = layout.literature_dir(project)
    _copy_if_absent(LITERATURE_REVIEW_TEMPLATE, lit / "literature_review_plan.md")
    _copy_if_absent(PAPER_REQUEST_TEMPLATE, lit / "paper_request_queue.md")
    _copy_if_absent(REPLANNING_MEMO_TEMPLATE, lit / "replanning_memo.md")

    # ── Copy template files → project root ───────────────────────────────────
    _copy_if_absent(PACKET_TEMPLATE, project / "research_run_packet.md")
    if PROJECT_README_TEMPLATE.exists():
        _copy_if_absent(PROJECT_README_TEMPLATE, project / "README.md")

    # ── Copy paper review index → literature/ ────────────────────────────────
    _copy_if_absent(PAPER_REVIEW_INDEX_TEMPLATE, project / "literature" / "index.md")

    # ── Write inline-content files (only if missing) ──────────────────────────
    for filename, content in INITIAL_GATES.items():
        target = gates / filename
        if not target.exists():
            target.write_text(content, encoding="utf-8")

    for filename, content in INITIAL_PLAN.items():
        target = plan / filename
        if not target.exists():
            target.write_text(content, encoding="utf-8")

    for filename, content in INITIAL_PROCESS.items():
        target = process / filename
        if not target.exists():
            target.write_text(content, encoding="utf-8")

    # ── Write .gitignore (refresh if missing) ─────────────────────────────────
    gitignore = project / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(_GITIGNORE_CONTENT, encoding="utf-8")

    # ── Write .claude/settings.local.json (hook registration) ─────────────────
    # Created only if absent so a researcher's custom permissions are preserved.
    claude_settings = project / ".claude" / "settings.local.json"
    if not claude_settings.exists():
        claude_settings.parent.mkdir(parents=True, exist_ok=True)
        claude_settings.write_text(_CLAUDE_SETTINGS_CONTENT, encoding="utf-8")

    # ── Write project-root marker ────────────────────────────────────────────
    project_root_mod.create_marker(project)

    # ── Bootstrap live workflow JSON + HTML so workflow_map.html opens immediately ──
    try:
        import update_live_json as ulj  # noqa: PLC0415
        ulj.bootstrap_project_json(project)
    except Exception:
        pass  # Non-fatal: agents can call update_live_json.py manually.

    try:
        import generate_workflow_map as gwm  # noqa: PLC0415
        gwm.write_outputs(project_root=project)
    except Exception:
        pass  # Non-fatal: researcher can run generate_workflow_map.py manually.

    return project


def _copy_if_absent(src: Path, dst: Path) -> None:
    """Copy `src` to `dst` only when `dst` does not already exist."""
    if dst.exists():
        return
    if not src.exists():
        return  # Optional template — skip silently if the harness lacks it.
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dst)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--project",
        type=Path,
        default=Path.cwd(),
        help="Directory to scaffold (default: current working directory). "
             "For a multi-thread project, point this at the per-thread subdir.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    project = scaffold_project(args.project)
    print(f"Initialized research project at {project}")
    print(f"  Marker:        {project_root_mod.MARKER_NAME}")
    print(f"  Workflow map:  {layout.workflow_map_html(project).relative_to(project)} "
          f"(open via a local http.server)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
